[package]
name = "openbands"
type = "bin"
authors = ["Stratos", "masaun"]
compiler_version = ">=1.0.0"
version = "0.1.2"

[dependencies]
# zkJWT
jwt = { tag = "saleel/deps-update-beta11", git = "https://github.com/zkemail/noir-jwt" }  # PR.15 of the noir-jwt repo, which is supposed to work with the Noir/Nargo v1.0.0-beta.11
#jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }

poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" } # From v1.0.0-beta.11 of Noir/Nargo, we need to use this module for Poseidon hash

# zkEmail
zkemail = { git = "https://github.com/masaun/zkemail.nr", tag = "feat/update-packages_nodash-v0.41.1", directory = "lib" }   # The original zkemail.nr package (version: "zkemail.nr_v.1.0.0-beta.5") with updated dependency (nodash v0.41.1)
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" } # This module is needed for the zkemail.nr package to work properly along with the nodash v0.41.1