[package]
name = "openbands"
type = "bin"
authors = ["Stratos", "masaun"]
compiler_version = ">=1.0.0"
version = "0.0.1"

[dependencies]
# zkJWT
#jwt = { tag = "v0.4.4", git = "https://github.com/saleel/noir-jwt" }
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }
#jwt = { path = "../noir-jwt_0.5.0" }

# zkEmail
zkemail = { git = "https://github.com/masaun/zkemail.nr", tag = "feat/update-packages_nodash-v0.41.1", directory = "lib" }   # The original zkemail.nr package (version: "zkemail.nr_v.1.0.0-beta.5") with updated dependency (nodash v0.41.1)
#zkemail = { path = "../zkemail.nr_feat-update-packages/lib" }   # [Result]: Successful to work
#zkemail = { path = "../zkemail.nr_v.1.0.0-beta.5/lib" }         # [Result]: Successful to work
#zkemail = { tag = "v1.0.0-beta.5", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" } # This module is needed for the zkemail.nr package to work properly along with the nodash v0.41.1.

# Openbanking.nr
openbanking_verifier = { tag = "feat/update-packages_nodash-v0.41.1_and_zkemail", git = "https://github.com/masaun/openbanking.nr-circuit", directory = "./lib" }
#openbanking_verifier = { path = "../openbanking_verifier" } # [Result]: Successful to work
#openbanking_verifier = { tag = "main", git = "https://github.com/attested-frontiers/openbanking.nr-circuit", directory = "./lib" }
#openbanking_verifier = { tag = "main", git = "https://github.com/Mach-34/openbanking-circuit/tree/feat/add-comments", directory = "./lib" }
