[package]
name = "openbands"
type = "bin"
authors = ["Stratos"]
compiler_version = ">=1.0.0"
version = "0.0.1"

[dependencies]
# zkJWT
jwt = { tag = "v0.4.4", git = "https://github.com/saleel/noir-jwt" }
#jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }
#jwt = { tag = "v0.5.0", path = "./libs/noir-jwt" }

# zkEmail
zkemail = { tag = "v0.4.3", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
#zkemail = { tag = "v0.4.3", path = "./libs/zkemail.nr" }

# Openbanking.nr
openbanking_verifier = { git = "https://github.com/attested-frontiers/openbanking.nr-circuit", directory = "./lib" }
#openbanking_verifier = { git = "https://github.com/Mach-34/openbanking-circuit/tree/feat/add-comments", directory = "./lib" }