[package]
name = "openbands"
type = "bin"
authors = ["Stratos", "masaun"]
compiler_version = ">=1.0.0"
version = "0.0.1"

[dependencies]
# zkJWT
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }

# zkEmail
zkemail = { git = "https://github.com/masaun/zkemail.nr", tag = "feat/update-packages_nodash-v0.41.1", directory = "lib" }   # The original zkemail.nr package (version: "zkemail.nr_v.1.0.0-beta.5") with updated dependency (nodash v0.41.1)Add commentMore actions
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" } # This module is needed for the zkemail.nr package to work properly along with the nodash v0.41.1.