[package]
name = "openbanking_verifier"
type = "lib"
compiler_version = ">=1.0.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.6.1"}
json_parser = { git = "https://github.com/noir-lang/noir_json_parser", tag = "v0.4.0" }
nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.40.2" }
rsa_pss = { git = "https://github.com/jp4g/noir_rsa_pss", tag = "main", directory = "lib" }
zkemail = { git = "https://github.com/zkemail/zkemail.nr", tag = "feat/update-packages", directory = "lib" } 

# zkJWT -> nargo test --show-output -> "nodash" error.
#jwt = { tag = "v0.5.0", git = "https://github.com/saleel/noir-jwt" }  
#jwt = { tag = "v0.4.4", git = "https://github.com/saleel/noir-jwt" }  

# zkEmail
#zkemail = { tag = "v0.4.3", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
zkemail = { tag = "v1.0.0-beta.5", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }