[package]
name = "openbanking_verifier"
type = "lib"
compiler_version = ">=1.0.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.6.1"}
json_parser = { git = "https://github.com/noir-lang/noir_json_parser", tag = "v0.4.0" }
nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.41.1" }
#nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.40.2" }
rsa_pss = { git = "https://github.com/jp4g/noir_rsa_pss", tag = "main", directory = "lib" }
zkemail = { git = "https://github.com/masaun/zkemail.nr", tag = "feat/update-packages_nodash-v0.41.1", directory = "lib" }   # The original zkemail.nr package (version: "zkemail.nr_v.1.0.0-beta.5") with updated dependency (nodash v0.41.1)
#zkemail = { path = "../zkemail.nr_v.1.0.0-beta.5/lib" }          # [Result]: Successful to work
#zkemail = { path = "../zkemail.nr_feat-update-packages/lib" }.   # [Result]: Successful to work
#zkemail = { git = "https://github.com/zkemail/zkemail.nr", tag = "feat/update-packages", directory = "lib" }  # The original 

# zkJWT (NOTE: This is just for testing purposes, not used in the circuit -> Hence, it's no problem if the line below to import noir-jwt module will be removed.)
jwt = { tag = "v0.5.0", git = "https://github.com/saleel/noir-jwt" }  
#jwt = { tag = "v0.4.4", git = "https://github.com/saleel/noir-jwt" }  