import zkeSDK, { Proof } from "@zk-email/sdk";  /// @dev - Import the zkEmail Blueprint SDK


/**
 * @notice - Generate a ZK Proof from the raw email, which is extracted from an EML file. 
 * @notice - The ZK proof is generated by using the zkEmail SDK.
 */
export async function generateProofFromEmlFile(
    rawEmail: string,
    blueprintSlug: string,
): Promise<{ proof: Proof }> {
      // Initialize the SDK
      const sdk = zkeSDK()

      // Get the blueprint
      const blueprint = await sdk.getBlueprint(blueprintSlug);

      // Create a prover
      const prover = blueprint.createProver();
      
      // Generate the proof
      const proof = await prover.generateProof(rawEmail);

      return { proof };
}